# Cuota definida en todo el NS
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
      pods: "10"
      # request: recursos mínimos para garantizar el servicio!
      requests.cpu: "250m" # 250 milicores = 1/4 core
      requests.memory: 100Mi
      requests.storage: 1000Mi
      # limit: nunca debe ser menor al request
      limits.cpu: "500m" # 500 milicores = 1/2 core
      limits.memory: 500Mi

      persistentvolumeclaims: "4"
      replicationcontrollers: "20"
      secrets: "10"
      services: "10"
      services.loadbalancers: "2"
