apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  storageClassName: ""
  claimRef:
    name: static-pvc
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany # N Nodos, N Pods
  persistentVolumeReclaimPolicy: Retain # delete
  hostPath:
    path: /logs/